name: Build kernel for WSL2
on:
  push: {}
  schedule:
    - cron: '30 5 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build toolchain
        run: sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev git libncurses-dev bc dwarves
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: microsoft/WSL2-Linux-Kernel
      - name: Create .config with AUDIT option
        run: sed -e 's/# CONFIG_AUDIT is not set/CONFIG_AUDIT=y/' Microsoft/config-wsl > .config
      - name: Make config
        run: make silentoldconfig
      - name: Make kernel
        run: make -j$[$(grep cpu.cores /proc/cpuinfo | sort -u | sed 's/[^0-9]//g') + 1]
      - name: Archive kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: arch/x86/boot/bzImage
